// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gen.proto

#include "gen.pb.h"
#include "gen.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Tests {

static const char* Test1ObjectService_method_names[] = {
  "/Tests.Test1ObjectService/Create",
  "/Tests.Test1ObjectService/ListenEvents",
  "/Tests.Test1ObjectService/TestMethod",
  "/Tests.Test1ObjectService/TestMethodSync",
  "/Tests.Test1ObjectService/TestMethodWithNoResponse",
  "/Tests.Test1ObjectService/TestMethodNoRequest",
  "/Tests.Test1ObjectService/SetPropertyPropString",
  "/Tests.Test1ObjectService/GetPropertyPropString",
  "/Tests.Test1ObjectService/SetPropertyPropComplex",
  "/Tests.Test1ObjectService/GetPropertyPropComplex",
};

std::unique_ptr< Test1ObjectService::Stub> Test1ObjectService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Test1ObjectService::Stub> stub(new Test1ObjectService::Stub(channel));
  return stub;
}

Test1ObjectService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Create_(Test1ObjectService_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_ListenEvents_(Test1ObjectService_method_names[1], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_TestMethod_(Test1ObjectService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TestMethodSync_(Test1ObjectService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TestMethodWithNoResponse_(Test1ObjectService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TestMethodNoRequest_(Test1ObjectService_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetPropertyPropString_(Test1ObjectService_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPropertyPropString_(Test1ObjectService_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetPropertyPropComplex_(Test1ObjectService_method_names[8], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPropertyPropComplex_(Test1ObjectService_method_names[9], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientReaderWriter< ::google::protobuf::Any, ::google::protobuf::Any>* Test1ObjectService::Stub::CreateRaw(::grpc::ClientContext* context) {
  return ::grpc_impl::internal::ClientReaderWriterFactory< ::google::protobuf::Any, ::google::protobuf::Any>::Create(channel_.get(), rpcmethod_Create_, context);
}

void Test1ObjectService::Stub::experimental_async::Create(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::google::protobuf::Any,::google::protobuf::Any>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderWriterFactory< ::google::protobuf::Any,::google::protobuf::Any>::Create(stub_->channel_.get(), stub_->rpcmethod_Create_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::google::protobuf::Any, ::google::protobuf::Any>* Test1ObjectService::Stub::AsyncCreateRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::google::protobuf::Any, ::google::protobuf::Any>::Create(channel_.get(), cq, rpcmethod_Create_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::google::protobuf::Any, ::google::protobuf::Any>* Test1ObjectService::Stub::PrepareAsyncCreateRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::google::protobuf::Any, ::google::protobuf::Any>::Create(channel_.get(), cq, rpcmethod_Create_, context, false, nullptr);
}

::grpc::ClientReader< ::google::protobuf::Any>* Test1ObjectService::Stub::ListenEventsRaw(::grpc::ClientContext* context, const ::Tests::Test1ListenEventStream& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::google::protobuf::Any>::Create(channel_.get(), rpcmethod_ListenEvents_, context, request);
}

void Test1ObjectService::Stub::experimental_async::ListenEvents(::grpc::ClientContext* context, ::Tests::Test1ListenEventStream* request, ::grpc::experimental::ClientReadReactor< ::google::protobuf::Any>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::google::protobuf::Any>::Create(stub_->channel_.get(), stub_->rpcmethod_ListenEvents_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::google::protobuf::Any>* Test1ObjectService::Stub::AsyncListenEventsRaw(::grpc::ClientContext* context, const ::Tests::Test1ListenEventStream& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::google::protobuf::Any>::Create(channel_.get(), cq, rpcmethod_ListenEvents_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::google::protobuf::Any>* Test1ObjectService::Stub::PrepareAsyncListenEventsRaw(::grpc::ClientContext* context, const ::Tests::Test1ListenEventStream& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::google::protobuf::Any>::Create(channel_.get(), cq, rpcmethod_ListenEvents_, context, request, false, nullptr);
}

::grpc::Status Test1ObjectService::Stub::TestMethod(::grpc::ClientContext* context, const ::Tests::Test1TestMethodMethodRequest& request, ::Tests::Test1TestMethodMethodResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_TestMethod_, context, request, response);
}

void Test1ObjectService::Stub::experimental_async::TestMethod(::grpc::ClientContext* context, const ::Tests::Test1TestMethodMethodRequest* request, ::Tests::Test1TestMethodMethodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TestMethod_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::TestMethod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1TestMethodMethodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TestMethod_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::TestMethod(::grpc::ClientContext* context, const ::Tests::Test1TestMethodMethodRequest* request, ::Tests::Test1TestMethodMethodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TestMethod_, context, request, response, reactor);
}

void Test1ObjectService::Stub::experimental_async::TestMethod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1TestMethodMethodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TestMethod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1TestMethodMethodResponse>* Test1ObjectService::Stub::AsyncTestMethodRaw(::grpc::ClientContext* context, const ::Tests::Test1TestMethodMethodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1TestMethodMethodResponse>::Create(channel_.get(), cq, rpcmethod_TestMethod_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1TestMethodMethodResponse>* Test1ObjectService::Stub::PrepareAsyncTestMethodRaw(::grpc::ClientContext* context, const ::Tests::Test1TestMethodMethodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1TestMethodMethodResponse>::Create(channel_.get(), cq, rpcmethod_TestMethod_, context, request, false);
}

::grpc::Status Test1ObjectService::Stub::TestMethodSync(::grpc::ClientContext* context, const ::Tests::Test1TestMethodSyncMethodRequest& request, ::Tests::Test1TestMethodSyncMethodResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_TestMethodSync_, context, request, response);
}

void Test1ObjectService::Stub::experimental_async::TestMethodSync(::grpc::ClientContext* context, const ::Tests::Test1TestMethodSyncMethodRequest* request, ::Tests::Test1TestMethodSyncMethodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TestMethodSync_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::TestMethodSync(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1TestMethodSyncMethodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TestMethodSync_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::TestMethodSync(::grpc::ClientContext* context, const ::Tests::Test1TestMethodSyncMethodRequest* request, ::Tests::Test1TestMethodSyncMethodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TestMethodSync_, context, request, response, reactor);
}

void Test1ObjectService::Stub::experimental_async::TestMethodSync(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1TestMethodSyncMethodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TestMethodSync_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1TestMethodSyncMethodResponse>* Test1ObjectService::Stub::AsyncTestMethodSyncRaw(::grpc::ClientContext* context, const ::Tests::Test1TestMethodSyncMethodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1TestMethodSyncMethodResponse>::Create(channel_.get(), cq, rpcmethod_TestMethodSync_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1TestMethodSyncMethodResponse>* Test1ObjectService::Stub::PrepareAsyncTestMethodSyncRaw(::grpc::ClientContext* context, const ::Tests::Test1TestMethodSyncMethodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1TestMethodSyncMethodResponse>::Create(channel_.get(), cq, rpcmethod_TestMethodSync_, context, request, false);
}

::grpc::Status Test1ObjectService::Stub::TestMethodWithNoResponse(::grpc::ClientContext* context, const ::Tests::Test1TestMethodWithNoResponseMethodRequest& request, ::Tests::Test1TestMethodWithNoResponseMethodResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_TestMethodWithNoResponse_, context, request, response);
}

void Test1ObjectService::Stub::experimental_async::TestMethodWithNoResponse(::grpc::ClientContext* context, const ::Tests::Test1TestMethodWithNoResponseMethodRequest* request, ::Tests::Test1TestMethodWithNoResponseMethodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TestMethodWithNoResponse_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::TestMethodWithNoResponse(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1TestMethodWithNoResponseMethodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TestMethodWithNoResponse_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::TestMethodWithNoResponse(::grpc::ClientContext* context, const ::Tests::Test1TestMethodWithNoResponseMethodRequest* request, ::Tests::Test1TestMethodWithNoResponseMethodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TestMethodWithNoResponse_, context, request, response, reactor);
}

void Test1ObjectService::Stub::experimental_async::TestMethodWithNoResponse(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1TestMethodWithNoResponseMethodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TestMethodWithNoResponse_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1TestMethodWithNoResponseMethodResponse>* Test1ObjectService::Stub::AsyncTestMethodWithNoResponseRaw(::grpc::ClientContext* context, const ::Tests::Test1TestMethodWithNoResponseMethodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1TestMethodWithNoResponseMethodResponse>::Create(channel_.get(), cq, rpcmethod_TestMethodWithNoResponse_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1TestMethodWithNoResponseMethodResponse>* Test1ObjectService::Stub::PrepareAsyncTestMethodWithNoResponseRaw(::grpc::ClientContext* context, const ::Tests::Test1TestMethodWithNoResponseMethodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1TestMethodWithNoResponseMethodResponse>::Create(channel_.get(), cq, rpcmethod_TestMethodWithNoResponse_, context, request, false);
}

::grpc::Status Test1ObjectService::Stub::TestMethodNoRequest(::grpc::ClientContext* context, const ::Tests::Test1TestMethodNoRequestMethodRequest& request, ::Tests::Test1TestMethodNoRequestMethodResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_TestMethodNoRequest_, context, request, response);
}

void Test1ObjectService::Stub::experimental_async::TestMethodNoRequest(::grpc::ClientContext* context, const ::Tests::Test1TestMethodNoRequestMethodRequest* request, ::Tests::Test1TestMethodNoRequestMethodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TestMethodNoRequest_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::TestMethodNoRequest(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1TestMethodNoRequestMethodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TestMethodNoRequest_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::TestMethodNoRequest(::grpc::ClientContext* context, const ::Tests::Test1TestMethodNoRequestMethodRequest* request, ::Tests::Test1TestMethodNoRequestMethodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TestMethodNoRequest_, context, request, response, reactor);
}

void Test1ObjectService::Stub::experimental_async::TestMethodNoRequest(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1TestMethodNoRequestMethodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TestMethodNoRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1TestMethodNoRequestMethodResponse>* Test1ObjectService::Stub::AsyncTestMethodNoRequestRaw(::grpc::ClientContext* context, const ::Tests::Test1TestMethodNoRequestMethodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1TestMethodNoRequestMethodResponse>::Create(channel_.get(), cq, rpcmethod_TestMethodNoRequest_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1TestMethodNoRequestMethodResponse>* Test1ObjectService::Stub::PrepareAsyncTestMethodNoRequestRaw(::grpc::ClientContext* context, const ::Tests::Test1TestMethodNoRequestMethodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1TestMethodNoRequestMethodResponse>::Create(channel_.get(), cq, rpcmethod_TestMethodNoRequest_, context, request, false);
}

::grpc::Status Test1ObjectService::Stub::SetPropertyPropString(::grpc::ClientContext* context, const ::Tests::Test1PropStringSetRequest& request, ::Tests::Test1PropStringSetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SetPropertyPropString_, context, request, response);
}

void Test1ObjectService::Stub::experimental_async::SetPropertyPropString(::grpc::ClientContext* context, const ::Tests::Test1PropStringSetRequest* request, ::Tests::Test1PropStringSetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SetPropertyPropString_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::SetPropertyPropString(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1PropStringSetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SetPropertyPropString_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::SetPropertyPropString(::grpc::ClientContext* context, const ::Tests::Test1PropStringSetRequest* request, ::Tests::Test1PropStringSetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SetPropertyPropString_, context, request, response, reactor);
}

void Test1ObjectService::Stub::experimental_async::SetPropertyPropString(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1PropStringSetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SetPropertyPropString_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1PropStringSetResponse>* Test1ObjectService::Stub::AsyncSetPropertyPropStringRaw(::grpc::ClientContext* context, const ::Tests::Test1PropStringSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1PropStringSetResponse>::Create(channel_.get(), cq, rpcmethod_SetPropertyPropString_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1PropStringSetResponse>* Test1ObjectService::Stub::PrepareAsyncSetPropertyPropStringRaw(::grpc::ClientContext* context, const ::Tests::Test1PropStringSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1PropStringSetResponse>::Create(channel_.get(), cq, rpcmethod_SetPropertyPropString_, context, request, false);
}

::grpc::Status Test1ObjectService::Stub::GetPropertyPropString(::grpc::ClientContext* context, const ::Tests::Test1PropStringGetRequest& request, ::Tests::Test1PropStringGetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetPropertyPropString_, context, request, response);
}

void Test1ObjectService::Stub::experimental_async::GetPropertyPropString(::grpc::ClientContext* context, const ::Tests::Test1PropStringGetRequest* request, ::Tests::Test1PropStringGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetPropertyPropString_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::GetPropertyPropString(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1PropStringGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetPropertyPropString_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::GetPropertyPropString(::grpc::ClientContext* context, const ::Tests::Test1PropStringGetRequest* request, ::Tests::Test1PropStringGetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetPropertyPropString_, context, request, response, reactor);
}

void Test1ObjectService::Stub::experimental_async::GetPropertyPropString(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1PropStringGetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetPropertyPropString_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1PropStringGetResponse>* Test1ObjectService::Stub::AsyncGetPropertyPropStringRaw(::grpc::ClientContext* context, const ::Tests::Test1PropStringGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1PropStringGetResponse>::Create(channel_.get(), cq, rpcmethod_GetPropertyPropString_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1PropStringGetResponse>* Test1ObjectService::Stub::PrepareAsyncGetPropertyPropStringRaw(::grpc::ClientContext* context, const ::Tests::Test1PropStringGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1PropStringGetResponse>::Create(channel_.get(), cq, rpcmethod_GetPropertyPropString_, context, request, false);
}

::grpc::Status Test1ObjectService::Stub::SetPropertyPropComplex(::grpc::ClientContext* context, const ::Tests::Test1PropComplexSetRequest& request, ::Tests::Test1PropComplexSetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SetPropertyPropComplex_, context, request, response);
}

void Test1ObjectService::Stub::experimental_async::SetPropertyPropComplex(::grpc::ClientContext* context, const ::Tests::Test1PropComplexSetRequest* request, ::Tests::Test1PropComplexSetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SetPropertyPropComplex_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::SetPropertyPropComplex(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1PropComplexSetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SetPropertyPropComplex_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::SetPropertyPropComplex(::grpc::ClientContext* context, const ::Tests::Test1PropComplexSetRequest* request, ::Tests::Test1PropComplexSetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SetPropertyPropComplex_, context, request, response, reactor);
}

void Test1ObjectService::Stub::experimental_async::SetPropertyPropComplex(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1PropComplexSetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SetPropertyPropComplex_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1PropComplexSetResponse>* Test1ObjectService::Stub::AsyncSetPropertyPropComplexRaw(::grpc::ClientContext* context, const ::Tests::Test1PropComplexSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1PropComplexSetResponse>::Create(channel_.get(), cq, rpcmethod_SetPropertyPropComplex_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1PropComplexSetResponse>* Test1ObjectService::Stub::PrepareAsyncSetPropertyPropComplexRaw(::grpc::ClientContext* context, const ::Tests::Test1PropComplexSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1PropComplexSetResponse>::Create(channel_.get(), cq, rpcmethod_SetPropertyPropComplex_, context, request, false);
}

::grpc::Status Test1ObjectService::Stub::GetPropertyPropComplex(::grpc::ClientContext* context, const ::Tests::Test1PropComplexGetRequest& request, ::Tests::Test1PropComplexGetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetPropertyPropComplex_, context, request, response);
}

void Test1ObjectService::Stub::experimental_async::GetPropertyPropComplex(::grpc::ClientContext* context, const ::Tests::Test1PropComplexGetRequest* request, ::Tests::Test1PropComplexGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetPropertyPropComplex_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::GetPropertyPropComplex(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1PropComplexGetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetPropertyPropComplex_, context, request, response, std::move(f));
}

void Test1ObjectService::Stub::experimental_async::GetPropertyPropComplex(::grpc::ClientContext* context, const ::Tests::Test1PropComplexGetRequest* request, ::Tests::Test1PropComplexGetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetPropertyPropComplex_, context, request, response, reactor);
}

void Test1ObjectService::Stub::experimental_async::GetPropertyPropComplex(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Tests::Test1PropComplexGetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetPropertyPropComplex_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1PropComplexGetResponse>* Test1ObjectService::Stub::AsyncGetPropertyPropComplexRaw(::grpc::ClientContext* context, const ::Tests::Test1PropComplexGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1PropComplexGetResponse>::Create(channel_.get(), cq, rpcmethod_GetPropertyPropComplex_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Tests::Test1PropComplexGetResponse>* Test1ObjectService::Stub::PrepareAsyncGetPropertyPropComplexRaw(::grpc::ClientContext* context, const ::Tests::Test1PropComplexGetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Tests::Test1PropComplexGetResponse>::Create(channel_.get(), cq, rpcmethod_GetPropertyPropComplex_, context, request, false);
}

Test1ObjectService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Test1ObjectService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Test1ObjectService::Service, ::google::protobuf::Any, ::google::protobuf::Any>(
          std::mem_fn(&Test1ObjectService::Service::Create), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Test1ObjectService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Test1ObjectService::Service, ::Tests::Test1ListenEventStream, ::google::protobuf::Any>(
          std::mem_fn(&Test1ObjectService::Service::ListenEvents), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Test1ObjectService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Test1ObjectService::Service, ::Tests::Test1TestMethodMethodRequest, ::Tests::Test1TestMethodMethodResponse>(
          std::mem_fn(&Test1ObjectService::Service::TestMethod), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Test1ObjectService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Test1ObjectService::Service, ::Tests::Test1TestMethodSyncMethodRequest, ::Tests::Test1TestMethodSyncMethodResponse>(
          std::mem_fn(&Test1ObjectService::Service::TestMethodSync), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Test1ObjectService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Test1ObjectService::Service, ::Tests::Test1TestMethodWithNoResponseMethodRequest, ::Tests::Test1TestMethodWithNoResponseMethodResponse>(
          std::mem_fn(&Test1ObjectService::Service::TestMethodWithNoResponse), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Test1ObjectService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Test1ObjectService::Service, ::Tests::Test1TestMethodNoRequestMethodRequest, ::Tests::Test1TestMethodNoRequestMethodResponse>(
          std::mem_fn(&Test1ObjectService::Service::TestMethodNoRequest), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Test1ObjectService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Test1ObjectService::Service, ::Tests::Test1PropStringSetRequest, ::Tests::Test1PropStringSetResponse>(
          std::mem_fn(&Test1ObjectService::Service::SetPropertyPropString), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Test1ObjectService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Test1ObjectService::Service, ::Tests::Test1PropStringGetRequest, ::Tests::Test1PropStringGetResponse>(
          std::mem_fn(&Test1ObjectService::Service::GetPropertyPropString), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Test1ObjectService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Test1ObjectService::Service, ::Tests::Test1PropComplexSetRequest, ::Tests::Test1PropComplexSetResponse>(
          std::mem_fn(&Test1ObjectService::Service::SetPropertyPropComplex), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Test1ObjectService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Test1ObjectService::Service, ::Tests::Test1PropComplexGetRequest, ::Tests::Test1PropComplexGetResponse>(
          std::mem_fn(&Test1ObjectService::Service::GetPropertyPropComplex), this)));
}

Test1ObjectService::Service::~Service() {
}

::grpc::Status Test1ObjectService::Service::Create(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::google::protobuf::Any, ::google::protobuf::Any>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Test1ObjectService::Service::ListenEvents(::grpc::ServerContext* context, const ::Tests::Test1ListenEventStream* request, ::grpc::ServerWriter< ::google::protobuf::Any>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Test1ObjectService::Service::TestMethod(::grpc::ServerContext* context, const ::Tests::Test1TestMethodMethodRequest* request, ::Tests::Test1TestMethodMethodResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Test1ObjectService::Service::TestMethodSync(::grpc::ServerContext* context, const ::Tests::Test1TestMethodSyncMethodRequest* request, ::Tests::Test1TestMethodSyncMethodResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Test1ObjectService::Service::TestMethodWithNoResponse(::grpc::ServerContext* context, const ::Tests::Test1TestMethodWithNoResponseMethodRequest* request, ::Tests::Test1TestMethodWithNoResponseMethodResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Test1ObjectService::Service::TestMethodNoRequest(::grpc::ServerContext* context, const ::Tests::Test1TestMethodNoRequestMethodRequest* request, ::Tests::Test1TestMethodNoRequestMethodResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Test1ObjectService::Service::SetPropertyPropString(::grpc::ServerContext* context, const ::Tests::Test1PropStringSetRequest* request, ::Tests::Test1PropStringSetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Test1ObjectService::Service::GetPropertyPropString(::grpc::ServerContext* context, const ::Tests::Test1PropStringGetRequest* request, ::Tests::Test1PropStringGetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Test1ObjectService::Service::SetPropertyPropComplex(::grpc::ServerContext* context, const ::Tests::Test1PropComplexSetRequest* request, ::Tests::Test1PropComplexSetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Test1ObjectService::Service::GetPropertyPropComplex(::grpc::ServerContext* context, const ::Tests::Test1PropComplexGetRequest* request, ::Tests::Test1PropComplexGetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Tests

